class_weights_all: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDwAAADEwMzQxNTUxNzQ1MTQyNHECWAYAAABjdWRhOjBxA03DAU50cQRRLoACXXEAWA8A
    AAAxMDM0MTU1MTc0NTE0MjRxAWEuwwEAAAAAAACdV7o/+e4FQvnuBUH57oVB0BbMP/nuhUEt6HQ/
    J0vWQPnuhUGf1+o+9pMyQZ4abj/2k7JAnVe6P/aTMkEidXE9xdyOPvnuhUFXthc++e4FQidL1kAB
    QYo/epLhPgk9JT1Z1yQ/+e4FQidL1kD57gVCJ0tWQDSCSD5Tbys/ellSPvnuhUH2kzJB+e6FQfXP
    QkD57gVC+e4FQfaTMkH57oVB9pMyQfnuhUFTb6s/+e6FQPnuhUH57gVB+e6FQfnuhUH57gVC+e4F
    Qp4abkAnS1ZA+e6FQSdL1kD57oVB9pMyQGm8nj/57oVBabyeP/nuBUL2kzJBLqRXPmm8Hj/57gVC
    sXs+PxtBhz32k7JA+e4FQvnuBUH2k7JA+e6FQPnuhUH57gVCnVe6PvaTskAnS1ZA9c9CQNAWzD/2
    kzJBhL++PPnuBUL57oVB+e4FQp/X6j2eGm5AU2+rP3qS4T8cEZk/+e6FPvnuBUIYmnM9LuUEPtRj
    vD72kzJBLhz8P51Xuj/2k7JAnhpuQDUPCD/57gVCU2+rP/nuhUH57gVC9pOyQC4c/D/57gVC+e4F
    QfaTskD2kzJBJ0vWQNAWzD/57gVC+e4FQsXcDkCeGm5A+e4FQvnuBUFZ1yRA+e4FQvnuBUL57gVC
    9pMyQObJkz757oVA+e4FQvnuhUH1z0JA+e4FQpHZGz/57gVCI7shP/nuBUH2kzJBHBGZQPnuhUAn
    S9ZA+e6FQVnXJECeGu4/6gvpPPnuhUH57gVB9pOyQPnuBUL2kzJB+e4FQvnuhUH57gVBn9fqPvnu
    hUGeGm5A6BBjPnqS4T/2k7JA9pOyQPnfgT757gVC9pMyQSdL1kD57gVC+e6FQSdLVkD2kzJBLhz8
    P/nuBUEBQYo++d+BP/aTMkH2kzJB+e4FQfnuBUKeGm4/WdckQPnuBUKeGm4+kzGxPfnuBUL57gVB
    nVe6Py3odD/57gVCxdwOQPnuBUL57oVB+e4FQp1Xuj/57oVBnVe6P/nuhUH57oVB+e4FQvaTMkEu
    HPw/LuWEPvnuBUKeGm5A9pMyQfXPQkD57gVCnhpuQPnuBUIuHHw/+e4FQvnuBUInS9ZAJ0vWQBwR
    mUD57oVAWdckQPnuhUH57gVC9pMyQeQSlT757oU/+e4FQrF7Pj8nS9ZA+e6FQfnuBUL57oVA+e4F
    QvnuBUL2kzJBHBGZQPnuBUIdjD8++e6FQfnuhUGR2Rs/J0vWQKRgNj9Z1yRA+e4FQvnuBUL57oVB
    9pMyQRwRmUAcEZlA+e4FQvnuBUL57gVBHBEZPxwRmUD57gVC+e6FQPnuBUHF3I4/9pOyQDKr5z72
    k7I/9pOyQFNvqz9TUtg9+e4FQidL1kBZ1yRA+e6FQfnuhUEcERlA+e4FQp4a7j/57gVB+e4FQXqS
    YT4cEZlA9pOyQPnuBUInS9ZAWdckQPnuBUL57oVB+e4FQidL1kD1z0JAnVc6P54abkD2kzJB+e6F
    QfnuBUL57oVBnhpuQPaTMkH2kzI/nhpuQCdL1j/57oVBN4UMP/nuhUH57gVBWdckQPnuhUH57gVC
    +e6FQfnuBULKEig/9pMyQPnuBUIuHPw/gVGpPZ4abj/F3A5A+e4FQlnXpD8cERlAHBGZQFnXJED5
    7gVCnhpuQPnuBUH57oVB+e6FQZ1Xuj81Dwg/J0vWQC4c/D72kzJB+e4FQvnuBUL95QA+9pOyQPnu
    hUHF3I4/+e4FQPnuBUL57oVB+e6FQSdLVkAnS9Y/xdyOP/nuhUH57oVA+e4FQvXPQkD1z0I/+e6F
    QfnuhUH57oVBepLhP/nuBUKkYDY+xdwOQPnuBUL2kzJB+e4FQfnuBUL57gVB+e4FQvnuBUL2k7JA
    +e4FQi4cfD8nS9ZAxdwOQJ4a7j/57gVBJ0tWQBwRmT/57gVCc0WjPvnuhUEnS9ZA+d+BP/aTskBI
    bj0+J0vWP7F7Pj/57gVCJ0vWQPnuBUEnS1ZAU2+rP/nuBUFzRaM++e4FQidL1kD57gVB+e4FQfnu
    BUL57gVC+e4FQkO2lj0nS9Y/+e4FQfnuBUL57oVBLhz8P3qS4T72kzJB9c9CQCdLVkD57oVAAUGK
    PzeFDD/57gVC9pOyQPnuBUIuHHw/+e4FQmr2VD72k7JAnhpuQObJkz/57gVC+e4FQvnfgT/2kzJB
    9pMyQfaTsj/57gVC9pOyQPnuBUIuHHw/+e4FQvnuhUH57oVB9pMyQfnuBUH57gVC9pMyQSdL1kD5
    7oVBDXGmPvXPQkD2kzJBHBEZQPnuBUJ6kuE/epLhP/aTMkH57oVB+e4FQvXPQkD57oVA9c9CP/nu
    BUL2k7JA+e4FQvnuBUKeGu4/nhpuQCdL1kD2k7I/+e6FQfnuBUL57gVC+e4FQfnuBUL57gVC+e4F
    QubJkz/57oVB
- 0
- !!python/tuple
  - 451
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
class_weights_genres: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDwAAADEwMzQxNTUxNzQ0ODU5MnECWAYAAABjdWRhOjBxA01FAk50cQRRLoACXXEAWA8A
    AAAxMDM0MTU1MTc0NDg1OTJxAWEuRQIAAAAAAADk0zhAt6JtQLei7T9g7k9BYO5PQQA5lz9NWKZA
    654KQWDuT0Bg7s9AYO5PQeueikBPbjs9YO5PQWDuz0Fg7k9BYO7PQeueikDrngpBYO7PQfWRDT9g
    7s9BYO7PQOTTOEC3ou0/YO7PQXpsnj9g7s9AYO7PQeTTuD9yu8w+YO7PQGDuT0GUGa8/TVimQFuI
    az5g7s9BYO7PQU1YpkBg7k8+YO7PP7eibUBg7k9BYO7PQXyjVj9g7s9B5NM4QGDuz0G3ou0/ssoH
    P01YpkBg7s9AYO7PQVePHD7rngpBYO7PQeueikB6bB4+YO5PQdpvdj+KSCM+EcvdP2Duz0Fg7s9B
    zfTxPmDuT0G3om1AYO5PQU/q/z9g7k9Bt6JtQGDuz0Fg7k9BEcvdP+ueikBg7s9AFdUzP2Duz0D6
    9Zg+YO7PQU1YpkDrngpBcROFP2Duz0Hk0zhA654KQWDuT0Fg7s9A654KQWDuz0Hk0zhAYO7PQbei
    7T/rngpBT+r/P2Duz0FVoUk/YO7PQbei7T9g7s9B654KQWDuz0HUpRA/YO5PQWDuT0EAORdAYO7P
    Qdpv9j5g7s8/VPtRPWDuz0DrnopAYO5PQdSlkD5g7s9A656KQOueCkFg7s9BYO7PQeueikCUGa8/
    YO7PQU1YpkBg7s9BbY3hPuTTOEDrngpBYO7PQWDuT0Bg7s8/TTvTPnEThT/UpZA/YO7PQOueCkFN
    WKZAYO7PQOueikBg7s9BYO7PPwaGlT4Ry90/YO7PQS2zwz8AOZc/lBmvP2Duzz9g7k9B2m92PmDu
    z0Hk07g/YO7PQeueikBg7k9BYO7PQQA5lz9xE4U/YO5PQU1YpkDUpRA/EcvdP1wRlDxg7s9BQW+x
    Pk1YpkDk0zhAQyhaPk/q/z9g7s9BlBmvP2DuT0EAORdAYO7PQWDuz0FxGD095NM4P7ei7T+UGS8/
    654KQGDuT0Fg7s9BYO5PQGDuz0HrnopAYO7PQU/q/z9g7k8/YO7PQGDuz0HrnopATVimQLeibUBV
    oUk/ADkXQOueikDrngpBYO7PQU1YJkC3ou0/YO7PQU/q/z8ts8M/t6LtP2Duz0Fg7k9BADkXQGDu
    T0HrngpBzfTxPeTTOECyyoc+YO5PQWDuz0Fg7k9AADkXQEMo2j5g7k9AYO7PQWDuz0Fg7s9BYO5P
    QGDuT0FP6v8/656KQOueCkFg7k9BLbNDP0/q/z+3om1A4ea0PGDuT0Fg7s9AYO7PQWDuT0Fg7k9B
    YO7PP2Duz0FNWKZA9ZENP2DuTz9NWCZAYO5PQXyj1j5NWKZALbPDPmDuz0Fg7k8/t6JtQLeibUB6
    bJ4+5NM4QGDuz0Bg7k9BYO5PQdSlkD+3om0/YO7PQeueCkFg7k9A654KQWDuT0Fg7s9BYO7PQeTT
    OEC3ou0/YO7PQWDuz0Fg7k9AYO5PQWDuT0FP6v8/lBmvP+ueikC3om0/TVgmQOueCkFg7s9BYO7P
    QXW9eD7rngpBEcvdP2Duz0EcVaA+QW+xPWDuz0Fg7s9B5NM4QOueCkFg7s9BTVimQGDuz0Fg7s9A
    YO5PQGDuz0Fg7k9A93BlP2DuT0FP6v8/YO5PQeueikDrngpATVgmQBHL3T9g7s9BTVimQOTTOEBP
    6n8/YO7PQeueCkHrngpBTVimQLbckz5g7s9BYO7PQWDuz0G3ou0/656KQE/q/z9g7s9B93BlP09u
    uz7N9PE+654KQU1YpkDrngpB5NM4QGDuT0Fg7s9A5NM4QBHL3T9g7k9BYO5PQeueikBg7k9AYO7P
    QWDuz0HrnopAMBb7PmDuz0HrngpBT+r/P+ueCkFg7k9BYO7PQWDuz0Fg7s9BTVimQGDuz0Fg7s9A
    YO7PQWDuz0Fg7s8/YO7PQE1YJkBP6v8/656KQLeibUBg7k9ATVimPwA5F0Ats8M+YO7PQU1YpkBg
    7s9A656KQOueij9g7s9BNZwqPmDuT0Hk0zhAYO7PQeueikBg7s9BYO7PQWDuz0FNWCZAzU8lPuTT
    uD9g7s9AYO7PQGDuz0HrnopAlBkvPk1YpkBg7k9BYO7PQU1YpkBg7s9AYO7PQbeibUDUpRA/TVim
    QE1YpkDk0zhAYO5PQU1YpkD3cGU/YO7PQWDuz0Fg7k9B654KQWDuz0BP6n8/654KQWDuz0Bg7k9B
    654KQdSlED9g7s9A5NM4QGDuT0Fg7s9Bt6LtPpQZrz9g7s9BYO5PQU1YpkDrngpBemweP+ueCkFg
    7s9BYO7PQGDuzz+3om0/EcvdP9tugz3k0zg/654KQU1YpkBP6v8/YO7PQU1YpkBNWKZAt6JtQGDu
    T0Fg7s9BYO5PQbeibUBg7s9AT+p/P2DuT0Fg7s8/YO7PQWDuz0HrngpBTVimQGDuT0Fg7k9ATVim
    QGDuz0Fg7s9BTVgmQBHL3T9g7k9AzfTxPS2zwz/1kQ0/fKNWPwA5F0Bg7k9BlBmvP2Duz0H3cGU/
    656KQGDuz0Fg7s9BYO5PQWDuz0Hk07g/YO7PQWDuT0Hab/Y+YO7PQWDuz0HUpZA/656KQGDuz0FN
    WKZAemyePy2zQz9den0+YO5PQbeibUBg7s9AADkXP2DuT0Hk07g/YO7PQWDuz0Fg7k9BADkXQGDu
    T0Fg7s9AYO7PQWDuT0Bg7s8/lQsTPmDuz0EAORdA+vUYPmDuz0Hk07g/YO7PQWDuz0EAORdA656K
    QGDuz0FNWCZAADmXP2Duz0Fg7s9BYO7PQNSlkD7M+mk9YO7PQWDuz0Hk07g/YO7PQWDuT0Fg7s9B
    YO5PQEMo2j5NWCZAYO7PQWDuz0Fg7s9BADkXQEIONT7rngpBYO7PP2Duz0Fg7k9BYO5PQWDuz0Hr
    ngpB2m92P2Duz0Bg7k9AYO5PQGDuz0HrnopAlBmvP0FvsT5g7s9BYO5PQQusAT1P6v8+YO5PQWDu
    z0Fg7s9BemyeP01YpkC3om1AYO7PQeueCkFNWCZAW4hrPmDuz0Bg7s9B654KQeueCkFg7s9A654K
    QU1YpkDUpZA+ADkXP2Duz0HrnopA5NM4QGDuT0HrngpBYO7PQWDuT0C3om0/YO5PPpQZrz9g7k9B
    YO7PQWDuz0HrngpBYO5PQQ==
- 0
- !!python/tuple
  - 581
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
class_weights_top: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDwAAADEwMzQxNTUxNzQ1MDMzNnECWAYAAABjdWRhOjBxA0sPTnRxBFEugAJdcQBYDwAA
    ADEwMzQxNTUxNzQ1MDMzNnEBYS4PAAAAAAAAAPG330E559I/7657QtrQqz7a0Ks+LLhIP+LDPj/n
    w7A/FastQHVGrEDcCrdBy+NgP9rQqz48wj9CvD9TQA==
- 0
- !!python/tuple
  - 15
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
learning_rate: 0.0001
num_classes_all: 451
num_classes_genres: 581
num_classes_top: 15
